default_install_hook_types:
  - "pre-push"
#  - "commit-msg"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args:
          - "--branch"
          - "master"
          - "--pattern"
          - "^(?!((feature\/|fix\/)?(MC-\\d{4,}|NO-TICKET|no-ticket|dependabot\/).*)).+"
        stages:
          - "push"
# -   repo: local
#     hooks:
#       - id: ticket-check
#         name: Commit message must start with the corresponding ticket number or NO-TICKET
#         language: pygrep
#         entry: '\A(?!(MC-\d{4,}|NO-TICKET)).+'
#         stages:
#           - "commit-msg"
