# example configuration file
# this config is not used on the cluster. If you are looking for the current version check:
# QA: https://github.com/bosch-rc-dev/kubernetes_config/blob/master/apps/qa/sdretriever/config.yml
tenant_blacklist:
  - TEST_TENANT
  - systestsrx
  - herbie
  - deviceprep
  - hacknorris
  - jackalope
  - rubber_duck
  - honeybadger
  - ridecare_companion_ces_stresstest
  - ridecare_companion_ces
training_whitelist:
  - datanauts
  - goaldiggers
  - deepsensation
  - srxfut3
  - ridecare_companion_fut
  - ridecare_companion_trial
recorder_blacklist:
  - FrontRecorder
discard_already_ingested: true
input_queue: dev-terraform-queue-download
