[tool.coverage.run]
omit = ["*/__init__.py"]
timid = true

[tool.pytest.ini_options]
python_files = ["test_*.py"]
addopts = "-m unit -v --cov-config=.coveragerc --cov=base --cov-report=xml"
markers = [
    "unit",
    "integration"
]

[tool.autopep8]
max_line_length = 120
recursive = true
aggressive = 3
diff = true

[tool.pylint]
recursive = true
load-plugins = [
    "pylint_quotes",
    "pylint_pydantic"
]

ignore-paths = [
  "tests/.*$",
]

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 120

[tool.pylint.pylint_quotes]
string-quote = "double"
triple-quote = "double"
docstring-quote = "double"

[tool.mypy]
files = [
    "base/**/*.py",
    "tests/**/*.py"
]
exclude = [
    "conftest.py",
]
plugins = [
    "pydantic.mypy"
]
# mypy per-module options:
[[tool.mypy.overrides]]
module = "setuptools"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "fiftyone"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "expiringdict"
ignore_missing_imports = true
[[tool.mypy.overrides]]
module = "moto"
ignore_missing_imports = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101"]
